import { IUser } from "../../models/user-modal";

export const users: IUser[] = [
  {
    id: 1,
    name: "Brad",
    avatar: "https://picsum.photos/40/40",
    position: "Electronics",
    email: "bfowley0@hatena.ne.jp",
    department: "Banks",
    status: "Active",
    portfolio: 100,
    role: "Employee",
    location: {
      country: "Indonesia",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 2,
    name: "Lexy",
    avatar: "https://picsum.photos/40/40",
    position: "Tools",
    email: "lcarty1@admin.ch",
    department: "Banks",
    status: "Active",
    portfolio: 25,
    role: "Owner",
    location: {
      country: "Greece",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 3,
    name: "Alfred",
    avatar: "https://picsum.photos/40/40",
    position: "Sports",
    email: "aaronovitz2@icio.us",
    department: "department Banks",
    status: "Active",
    portfolio: 40,
    role: "Employee",
    location: {
      country: "Burkina Faso",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 4,
    name: "Kynthia",
    avatar: "https://picsum.photos/40/40",
    position: "Clothing",
    email: "kmccurley3@symantec.com",
    department: "Power Generation",
    status: "Active",
    portfolio: 23,
    role: "Employee",
    location: {
      country: "Thailand",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 5,
    name: "Cristal",
    avatar: "https://picsum.photos/40/40",
    position: "Electronics",
    email: "cdelhay4@people.com.cn",
    department: "Electrical Products",
    status: "Active",
    portfolio: 75,
    role: "Employee",
    location: {
      country: "China",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 6,
    name: "Jessee",
    avatar: "https://picsum.photos/40/40",
    position: "Automotive",
    email: "jhillaby5@youtube.com",
    department: "department Pharmaceuticals",
    status: "Active",
    portfolio: 78,
    role: "Employee",
    location: {
      country: "Brazil",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 7,
    name: "Noak",
    avatar: "https://picsum.photos/40/40",
    position: "Toys",
    email: "nmckag6@t-online.de",
    department: "n/a",
    status: "Active",
    portfolio: 76,
    role: "Employee",
    location: {
      country: "Peru",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 8,
    name: "Gerladina",
    avatar: "https://picsum.photos/40/40",
    position: "Electronics",
    email: "gfolkard7@abc.net.au",
    department: "Air Freight/Delivery Services",
    status: "Active",
    portfolio: 57,
    role: "Employee",
    location: {
      country: "France",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 9,
    name: "Dorree",
    avatar: "https://picsum.photos/40/40",
    position: "Books",
    email: "dtunny8@engadget.com",
    department: "Biotechnology: Commercial Physical & Biological Resarch",
    status: "Active",
    portfolio: 98,
    role: "Employee",
    location: {
      country: "China",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 10,
    name: "Estelle",
    avatar: "https://picsum.photos/40/40",
    position: "Automotive",
    email: "eovery9@wisc.edu",
    department: "Food Chains",
    status: "Active",
    portfolio: 83,
    role: "Owner",
    location: {
      country: "China",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 11,
    name: "Elsi",
    avatar: "https://picsum.photos/40/40",
    position: "Garden",
    email: "eberkerya@youtube.com",
    department: "n/a",
    status: "Active",
    portfolio: 67,
    role: "Employee",
    location: {
      country: "Philippines",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 12,
    name: "Constantine",
    avatar: "https://picsum.photos/40/40",
    position: "Outdoors",
    email: "civashnyovb@ihg.com",
    department: "Industrial Specialties",
    status: "Active",
    portfolio: 66,
    role: "Employee",
    location: {
      country: "Sierra Leone",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 13,
    name: "Brenna",
    avatar: "https://picsum.photos/40/40",
    position: "Movies",
    email: "bmustonc@pbs.org",
    department: "Finance: Consumer Services",
    status: "Active",
    portfolio: 95,
    role: "Employee",
    location: {
      country: "China",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 14,
    name: "Revkah",
    avatar: "https://picsum.photos/40/40",
    position: "Jewelry",
    email: "rguerryd@illinois.edu",
    department: "EDP Services",
    status: "Active",
    portfolio: 69,
    role: "Employee",
    location: {
      country: "Turkmenistan",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 15,
    name: "Baily",
    avatar: "https://picsum.photos/40/40",
    position: "Beauty",
    email: "bgrime@cafepress.com",
    department: "Professional Services",
    status: "Active",
    portfolio: 87,
    role: "Employee",
    location: {
      country: "Dominican Republic",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 16,
    name: "Giuseppe",
    avatar: "https://picsum.photos/40/40",
    position: "Kids",
    email: "gminchellaf@domainmarket.com",
    department: "Computer Manufacturing",
    status: "Suspended",
    portfolio: 25,
    role: "Owner",
    location: {
      country: "Indonesia",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 17,
    name: "Marrissa",
    avatar: "https://picsum.photos/40/40",
    position: "Industrial",
    email: "mkaubischg@narod.ru",
    department: "department Pharmaceuticals",
    status: "Active",
    portfolio: 25,
    role: "Owner",
    location: {
      country: "Canada",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 18,
    name: "Elvira",
    avatar: "https://picsum.photos/40/40",
    position: "Electronics",
    email: "eingh@posterous.com",
    department: "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
    status: "Pending",
    portfolio: 25,
    role: "Owner",
    location: {
      country: "Indonesia",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 19,
    name: "Niel",
    avatar: "https://picsum.photos/40/40",
    position: "Books",
    email: "nkassidyi@indiatimes.com",
    department: "Computer Software: Prepackaged Software",
    status: "Pending",
    portfolio: 25,
    role: "Owner",
    location: {
      country: "Spain",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 20,
    name: "Colene",
    avatar: "https://picsum.photos/40/40",
    position: "Computers",
    email: "cvautreyj@de.vu",
    department: "Clothing/Shoe/Accessory Stores",
    status: "Active",
    portfolio: 25,
    role: "Employee",
    location: {
      country: "Indonesia",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 21,
    name: "Barty",
    avatar: "https://picsum.photos/40/40",
    position: "Sports",
    email: "bolenovk@pcworld.com",
    department: "Multi-Sector Companies",
    status: "Active",
    portfolio: 55,
    role: "Employee",
    location: {
      country: "China",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 22,
    name: "Leshia",
    avatar: "https://picsum.photos/40/40",
    position: "Shoes",
    email: "lnunanl@nifty.com",
    department: "n/a",
    status: "Active",
    portfolio: 25,
    role: "Employee",
    location: {
      country: "Philippines",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 23,
    name: "Wynny",
    avatar: "https://picsum.photos/40/40",
    position: "Kids",
    email: "weickhoffm@japanpost.jp",
    department: "Oil & Gas Production",
    status: "Suspended",
    portfolio: 34,
    role: "Employee",
    location: {
      country: "China",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 24,
    name: "Kameko",
    avatar: "https://picsum.photos/40/40",
    position: "Books",
    email: "kreightleyn@elpais.com",
    department: "Telecommunications Equipment",
    status: "Active",
    portfolio: 25,
    role: "Employee",
    location: {
      country: "Finland",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
  {
    id: 25,
    name: "Thorny",
    avatar: "https://picsum.photos/40/40",
    position: "Movies",
    email: "thullso@dot.gov",
    department: "Professional Services",
    status: "Pending",
    portfolio: 55,
    role: "Employee",
    location: {
      country: "Poland",
      city: "",
      address: "",
    },
    isFocus: false,
    account_type: "Individual",
    phone: "",
  },
];
